chore: Upgrade to netstandard 2.1 and netcore3.1
syncromatics/Akka.Monitoring.Prometheus pull request #4
Opened 2020-10-26 09:45 UTC by nicolastakashi

In order to solve issue #3, could you guys take a look and let me know about these changes?

2020-10-28 18:07 UTC, thzinc requested changes
Thanks for contributing this! I have a couple of comments/questions, but this is looking good overall.

2020-10-29 07:24 UTC, nicolastakashi commented on .idea/.idea.Akka.Monitoring.Prometheus/.idea/contentModel.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Sure about that, I forgot to remove it.
I will introduce some rules in the git ignore file in order to avoid it happens again.

2020-10-29 07:25 UTC, nicolastakashi commented on src/Akka.Monitoring.Prometheus/Akka.Monitoring.Prometheus.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
Sure right!
Makes sense to me :D

2020-10-29 19:04 UTC, thzinc approved these changes
This looks great! Thanks for contributing this!

2020-10-29 19:04 UTC, merged

2020-10-29 19:05 UTC, thzinc commented
closes #3 (effectively)